name: Docker Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t hello-world .

      - name: Show Success
        run: echo "✅ L'image Docker a été construite avec succès !"

